GET http://localhost:8080/api/chirps HTTP/1.1
content-type: application/json

# {
#   "email": "johndoe2@example.com"
# }

{
  "body": "If you're committed enough, you can make any story work.",
  "user_id": "a1263b77-46a7-459e-8bc0-7ddcdd7200dd"
}